### ISSUE TITLE
[ Suggestion ] Sort function performance dump table alphabetically.

### ISSUE THREAD

**Issue by SnaveSutit** [Trivaxy/datamancer#2]
As the title says. It would be wonderful to have the profiled functions table be sorted alphabetically.

**Comment by Trivaxy** [comment]
There'll likely be a config option to decide how the user wants to sort (ascending or descending, and by which column)

**Comment by Trivaxy** [comment]
Implemented in 5e42382. Sorting can now be specified in the command itself (e.g. `/fprofile dump name descending`)
